on:
  push:
    branches:
    - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: pip install pytest playwright pytest-playwright

      - name: Install browsers
        run: python -m playwright install

      - name: Run tests (chromium)
        run: pytest --browser chromium

      - name: Run tests (firefox)
        run: pytest --browser firefox

      - name: Run tests (webkit)
        run: pytest --browser webkit
